const SENTENCES:string[] = [
    "The sun dipped below the horizon.",
    "She poured coffee into her favorite mug.",
    "A cat meowed softly at the window.",
    "The wind carried the scent of rain.",
    "He walked barefoot across the wet grass.",
    "They danced under the stars all night.",
    "The bakery smelled like fresh cinnamon rolls.",
    "She laughed until her stomach hurt.",
    "The forest was silent except for birds.",
    "He found an old photo in the drawer.",
    "The waves crashed against the rocky shore.",
    "A child chased butterflies in the garden.",
    "His jacket was too thin for the weather.",
    "She whispered a secret into his ear.",
    "The sky turned orange at sunset.",
    "They waited in line for the concert.",
    "The snow fell quietly over the hills.",
    "He carried the box up the stairs.",
    "Her smile lit up the whole room.",
    "The room smelled faintly of lavender.",
    "He whistled a tune as he walked.",
    "The candle flickered in the dark.",
    "A dog barked in the distance.",
    "She folded the letter and sighed.",
    "They cheered when the goal was scored.",
    "A train rumbled in the distance.",
    "He watched the rain hit the window.",
    "She wore a red scarf around her neck.",
    "The ice cream melted in the sun.",
    "A bird flew past the open window.",
    "The floor creaked beneath his feet.",
    "The smell of popcorn filled the air.",
    "She hummed her favorite song.",
    "The balloon floated away into the sky.",
    "He tripped over a loose stone.",
    "They sat around a warm campfire.",
    "The sky was filled with clouds.",
    "He handed her a bouquet of roses.",
    "A squirrel darted up the tree.",
    "The stars looked bright tonight.",
    "She opened the book and began to read.",
    "He left his umbrella on the train.",
    "The soup was too hot to eat.",
    "A leaf drifted slowly to the ground.",
    "She tied her hair into a bun.",
    "The bus arrived five minutes late.",
    "He whistled while walking down the street.",
    "The bell rang loudly in the hallway.",
    "They shared a slice of cheesecake.",
    "Her boots were muddy from the trail.",
    "A plane flew low overhead."
]

export default SENTENCES